# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/content/menus

main:
    - label: Inicio
      title: Página de inicio
      path: homepage
    - label: Noticias
      path: entradas
    - label: Contacto
      title: Página de contacto
      path: pagina/contacto
    - label: Anexsoft Blog
      link: http://anexsoft.com