# This file defines the different types of taxonomies in Bolt. See the
# documentation for details: https://docs.bolt.cm/content/taxonomies

tags:
    slug: tags
    singular_slug: tag
    behaves_like: tags
    postfix: "Add some freeform tags. Start a new tag by typing a comma or space."
    allow_spaces: false
    #listing_template: tag-listing.twig #custom template

groups:
    slug: groups
    singular_slug: group
    behaves_like: grouping
    options: { main: "The main group", meta: "Meta group", other: "The other stuff" }
    has_sortorder: true

categories:
    name: Categorías
    slug: categories
    singular_name: Categoría
    singular_slug: categories
    behaves_like: categories
    multiple: true
    options: [ Front-End, Back-End, Otros ]
